name: Create Archive
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Make release archive
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'opencart-3-begateway-payment-module.ocmod.zip'
        exclusions: '*.git* docker* LICENSE* Makefile README* *.zip /*docker/*'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "opencart-3-begateway-payment-module.ocmod.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
